version: '3.8'  # 指定 Docker Compose 文件的版本
services:
  elasticsearch:
    image: elasticsearch:8.7.0
    container_name: elasticsearch8.7.0
    hostname: elasticsearch8
    privileged: true
    tty: true
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - es_network
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: kibana:8.7.0
    container_name: kibana8.7.0
    hostname: elasticsearch8
    restart: always
    privileged: true
    tty: true
    # volumes:
      # - ./etc/localtime:/etc/timezone
      # - ./etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - es_network
networks:
  es_network:
    driver: bridge
