spring:
  elasticsearch:
    uris: http://es:9200
    username: elastic
    password: M9VhXO063NGdy=X8IQpV 
  data:
    redis:
      host: email-redis
      port: 6379
      database: 0
      password: M9VhXO063NGdy=X8IQpV




