spring:
   main:
     allow-bean-definition-overriding: true

   servlet:
     multipart:
       enabled: true
       max-file-size: 10MB
       max-request-size: 10MB
       resolve-lazily: true
       location: ${java.io.tmpdir}
   mvc:
     pathmatch:
       matching-strategy: ant_path_matcher
  #  profiles:
  #   active: prod
   data:
       redis:
           host: 112.35.176.43
           port: 9500
           database: 0
server:
   tomcat:
     max-swallow-size: -1

elasticsearch:
  host: 112.35.176.43
  port: 9201
  scheme: http