server:
  port: 8080

spring:
  elasticsearch:
    uris: http://es:9200
    username: elastic
    password: M9VhXO063NGdy=X8IQpV
    connection-timeout: 50000
    socket-timeout: 50000


  data:
    redis:
      host: email-redis
      port: 6379
      database: 0
      password: M9VhXO063NGdy=X8IQpV