server:
  port: 8080

spring:
  elasticsearch:
    uris: http://112.35.176.43:9201
#    uris: http://localhost:9200

  data:
    redis:
#      host: localhost
#      port: 6379
      host: 112.35.176.43
      port: 9500