spring:
  main:
    allow-bean-definition-overriding: true
  elasticsearch:
    uris: http://localhost:9200
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: true
      location: ${java.io.tmpdir}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  tomcat:
    max-swallow-size: -1 