spring:
   main:
     allow-bean-definition-overriding: true

   servlet:
     multipart:
       enabled: true
       max-file-size: 20MB
       max-request-size: 20MB
       resolve-lazily: true
       location: ${java.io.tmpdir}
   mvc:
     pathmatch:
       matching-strategy: ant_path_matcher
   profiles:
     active: prod
   data:
       redis:
           host: email-redis
           port: 6379
           database: 0
           password: M9VhXO063NGdy=X8IQpV
elasticsearch:
 host: es
 port: 9200
 scheme: http
 username: elastic
 password: M9VhXO063NGdy=X8IQpV
server:
   tomcat:
     max-swallow-size: -1

