#\u6570\u636E\u5E93\u914D\u7F6E
spring:
  config:
    activate:
      on-profile: test
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5000
    socket-timeout: 5000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 9898


