netty:
  port: 8888
  bossThreads: 1
  workerThreads: 4
  backlog: 128
  keepAlive: true
  maxContentLength: 65536
spring:
  elasticsearch:
    uris: http://112.35.176.43:9201
    connection-timeout: 5000
    socket-timeout: 5000
#  data:
#    redis:
#      host: 112.35.176.43
#      port: 9500
#      database: 0
elasticsearch:
  host: 112.35.176.43
  port: 9201
  #username:   # ES 用户名
  #password:   # ES 密码
