netty:
  port: 8080
  bossThreads: 1
  workerThreads: 4
  backlog: 128
  keepAlive: true
  maxContentLength: 65536
spring:
  elasticsearch:
    uris: http://112.35.176.43:9201
#    uris: http://es:9200
    connection-timeout: 5000
    socket-timeout: 5000
#    data:
#      redis:
#        host: 112.35.176.43
#        port: 9500
#        database: 0

elasticsearch:
  host: 112.35.176.43
  port: 9201
  username: elastic
  password: M9VhXO063NGdy=X8IQpV

#  data:
#    redis:
#      host: email-redis
#      port: 6379
#      database: 0
#elasticsearch:
#  host: es
#  port: 9200
#  username: elastic  # ES 用户名
#  password: M9VhXO063NGdy=X8IQpV # ES 密码
server:
  port: 8888
