netty:
  port: 8888
  bossThreads: 1
  workerThreads: 4
  backlog: 128
  keepAlive: true
  maxContentLength: 65536

elasticsearch:
  host: 112.35.176.43
  port: 9201
  #username:   # ES 用户名
  #password:   # ES 密码
